# fly.toml app configuration file generated for lords-legends-character-creator on 2024-11-14T01:00:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lords-legends-character-creator'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
